name: 'Amplify Simple Deployment Action'
description: 'GitHub action creates a deployment into an existing Amplify aplication'
branding:
  color: yellow
  icon: at-sign
inputs:
  appId:
    description: Amplify Application ID
    required: true
  branchName:
    description: Amplify Application branch to deploy
    required: true
  artifactPath:
    description: Path where the artifact is located to be deployed
    required: true
  region:
    description: Region of the Amplify Application
    required: true
outputs:
  jobId:
    description: 'Final Job Id that was generated after a deployment request'

runs:
  using: node16
  main: dist/index.js